language: rust

os:
  - linux
  - osx

rust: stable

before_install:
    - sudo apt-get install -y mingw-w64

before_script:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then curl -O https://static.rust-lang.org/dist/rust-std-1.6.0-x86_64-pc-windows-gnu.tar.gz; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then tar xf rust-std-1.6.0-x86_64-pc-windows-gnu.tar.gz; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then mv rust-std-1.6.0-x86_64-pc-windows-gnu/rust-std-x86_64-pc-windows-gnu/lib/rustlib/x86_64-pc-windows-gnu ~/rust/lib/rustlib/; fi

script:
  - make test
  - if [[ $TRAVIS_OS_NAME == "osx"   ]]; then make release_osx64; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then make release_lnx64; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then make release_win64; fi

deploy:
  provider: releases
  api_key:
    secure: s5+CiyxfZQn42/e3QpsnZugg5CR+hmtS6Bv92JqFDfmlYep6DIZmCmZ4S5RqVKplB0NyF5zj3XWSyOhlHRYjoVctwZa4YNqUgSo2fQh1U+hPawNcsq3Bv84rnYnNDQMKQXjfBzb/8UL3WI+deN96FAfOeSMNwkfmexvm3XFq4uQirQBjy2CW1AF8R7ZWKsuH62j5nLWRYveVXhqc+Ao45SUp+XZN36ioNnJq7BdeneVAIjWHtEzJVXt+Z4yGQvRjGeZWMteSv+1cgzb6hje2qeYxlu4efr9gV/nUlpLe9DTFBttoLsrgyJclCjaOjcvsKw87inbNwuPsA4eK6oaBlJ/cMU0UI0v8kZ3JxGY7VD0iCKWD8V1HjesznUfdrgyvWkHtQUNkd4JC04LLsXpJpv9iBQBwSFzSlC5Z3YoV+TEiyWE4e2MZfwEgYHCmyK7Q+3NXKKkgiZ6T06mchFWnym/I0sP+A/egfdxpggdkbdgv9zs8EB95ecATLyn7LhrH3yzQ3kB6IGX584TbQAS9rLvm4quyU9BSuBH0c0N7CwTS2b+PQsH8dHiphbOFZtoqUIh9Y83RNqNBbqbfe5coc1oRZM7SRxlS1VIc0Ml93n50eZDO8QivqJnYFjJHDkOPsphyj47lOQPnRlrr3GXQvsR0ZoGr5tO88FTgjZDVjsU=
  file:
    - amber-*.zip
  file_glob: true
  on:
    repo: dalance/amber
    tags: true
