branches:
    except:
        - gh-pages

platform:
    - x64

environment:
    RUST_INSTALL_DIR: C:\Rust
    matrix:
        - RUST_INSTALL_TRIPLE: i686-pc-windows-msvc
          RUST_VERSION: 1.6.0
        - RUST_INSTALL_TRIPLE: x86_64-pc-windows-msvc
          RUST_VERSION: 1.6.0

install:
    - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:RUST_VERSION}-${env:RUST_INSTALL_TRIPLE}.exe"
    - cmd: rust-%RUST_VERSION%-%RUST_INSTALL_TRIPLE%.exe /VERYSILENT /NORESTART /DIR="%RUST_INSTALL_DIR%"
    - cmd: SET PATH=%RUST_INSTALL_DIR%\bin

build: false
test_script:
    - cmd: cargo test
    - cmd: cargo build --release --target=%RUST_INSTALL_TRIPLE%
