branches:
    except:
        - gh-pages

platform:
    - x64

environment:
  matrix:
    - TARGET: i686-pc-windows-msvc
      CHANNEL: stable
      ARCH: i686
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable
      ARCH: x86_64

install:
    - curl -sSf -o rustup-init.exe https://win.rustup.rs
    - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
    - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
    - rustc -Vv
    - cargo -V

build: false

build_script:
    - cmd: cargo build --release --target=%TARGET%

after_build:
    - cmd: 7z a amber-%APPVEYOR_REPO_TAG_NAME%-%ARCH%-win.zip %APPVEYOR_BUILD_FOLDER%\target\%TARGET%\release\amb*.exe

test_script:
    - cmd: cargo test

artifacts:
    - path: amber*.zip
      name: amber

deploy:
    provider: GitHub
    auth_token:
        secure: kS4UP3hsDNOgREPMBXARyppuvv5D9BKEBJClvqPF0Q347VqAD0T3po5TaZjpBFqr
    artifact: /.*\.zip/
    on:
        branch: /v\d+\.\d+\.\d+/
        appveyor_repo_tag: true
