[package]
name = "amber"
version = "0.2.0"
authors = ["dalance@gmail.com"]
repository = "https://github.com/dalance/amber"
keywords = ["search", "replace"]
license = "MIT"
readme = "README.md"
description = "A code search and replace tool"

[[bin]]
name = "ambr"
path = "src/ambr.rs"

[[bin]]
name = "ambs"
path = "src/ambs.rs"

[features]
sse = []

[dependencies]
docopt            = "*"
memmap            = "*"
num_cpus          = "*"
regex             = "*"
rand              = "*"
rustc-serialize   = "*"
scoped_threadpool = "*"
tempfile          = "*"
term              = "*"
time              = "*"

[profile.dev]
opt-level        = 0
debug            = true
rpath            = false
lto              = false
debug-assertions = true
codegen-units    = 1

[profile.release]
opt-level        = 3
debug            = false
rpath            = false
lto              = false
debug-assertions = false
codegen-units    = 1

[profile.test]
opt-level        = 3
debug            = false
rpath            = false
lto              = false
debug-assertions = false
codegen-units    = 1

