[package]
name = "amber"
version = "0.2.0"
authors = ["dalance@gmail.com"]
repository = "https://github.com/dalance/amber"
keywords = ["search", "replace"]
license = "MIT"
readme = "README.md"
description = "A code search and replace tool"

[[bin]]
name = "ambr"
path = "src/ambr.rs"

[[bin]]
name = "ambs"
path = "src/ambs.rs"

[features]
sse = []

[dependencies]
docopt            = "0.6.78"
glob              = "*"
memmap            = "0.2.3"
num_cpus          = "0.2.10"
regex             = "0.1.47"
rand              = "0.3.13"
rlibc             = "*"
rustc-serialize   = "0.3.16"
scoped_threadpool = "0.1.6"
tempfile          = "2.0.1"
term              = "0.4.4"
time              = "0.1.34"

[profile.dev]
opt-level        = 0
debug            = true
rpath            = false
lto              = false
debug-assertions = true
codegen-units    = 1

[profile.release]
opt-level        = 3
debug            = false
rpath            = false
lto              = false
debug-assertions = false
codegen-units    = 1

[profile.test]
opt-level        = 3
debug            = false
rpath            = false
lto              = false
debug-assertions = false
codegen-units    = 1

